#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=1}] slot.weapon.mainhand 0 vc:slime_ball 1 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=2}] slot.weapon.mainhand 0 vc:slime_ball 2 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=3}] slot.weapon.mainhand 0 vc:slime_ball 3 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=4}] slot.weapon.mainhand 0 vc:slime_ball 4 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=5}] slot.weapon.mainhand 0 vc:slime_ball 5 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=6}] slot.weapon.mainhand 0 vc:slime_ball 6 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=7}] slot.weapon.mainhand 0 vc:slime_ball 7 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=8}] slot.weapon.mainhand 0 vc:slime_ball 8 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=9}] slot.weapon.mainhand 0 vc:slime_ball 9 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=10}] slot.weapon.mainhand 0 vc:slime_ball 10 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=11}] slot.weapon.mainhand 0 vc:slime_ball 11 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=12}] slot.weapon.mainhand 0 vc:slime_ball 12 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=13}] slot.weapon.mainhand 0 vc:slime_ball 13 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=14}] slot.weapon.mainhand 0 vc:slime_ball 14 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=15}] slot.weapon.mainhand 0 vc:slime_ball 15 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=16}] slot.weapon.mainhand 0 vc:slime_ball 16 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=17}] slot.weapon.mainhand 0 vc:slime_ball 17 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=18}] slot.weapon.mainhand 0 vc:slime_ball 18 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=19}] slot.weapon.mainhand 0 vc:slime_ball 19 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=20}] slot.weapon.mainhand 0 vc:slime_ball 20 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=21}] slot.weapon.mainhand 0 vc:slime_ball 21 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=22}] slot.weapon.mainhand 0 vc:slime_ball 22 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=23}] slot.weapon.mainhand 0 vc:slime_ball 23 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=24}] slot.weapon.mainhand 0 vc:slime_ball 24 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=25}] slot.weapon.mainhand 0 vc:slime_ball 25 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=26}] slot.weapon.mainhand 0 vc:slime_ball 26 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=27}] slot.weapon.mainhand 0 vc:slime_ball 27 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=28}] slot.weapon.mainhand 0 vc:slime_ball 28 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=29}] slot.weapon.mainhand 0 vc:slime_ball 29 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=30}] slot.weapon.mainhand 0 vc:slime_ball 30 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=31}] slot.weapon.mainhand 0 vc:slime_ball 31 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=32}] slot.weapon.mainhand 0 vc:slime_ball 32 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=33}] slot.weapon.mainhand 0 vc:slime_ball 33 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=34}] slot.weapon.mainhand 0 vc:slime_ball 34 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=35}] slot.weapon.mainhand 0 vc:slime_ball 35 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=36}] slot.weapon.mainhand 0 vc:slime_ball 36 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=37}] slot.weapon.mainhand 0 vc:slime_ball 37 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=38}] slot.weapon.mainhand 0 vc:slime_ball 38 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=39}] slot.weapon.mainhand 0 vc:slime_ball 39 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=40}] slot.weapon.mainhand 0 vc:slime_ball 40 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=41}] slot.weapon.mainhand 0 vc:slime_ball 41 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=42}] slot.weapon.mainhand 0 vc:slime_ball 42 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=43}] slot.weapon.mainhand 0 vc:slime_ball 43 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=44}] slot.weapon.mainhand 0 vc:slime_ball 44 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=45}] slot.weapon.mainhand 0 vc:slime_ball 45 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=46}] slot.weapon.mainhand 0 vc:slime_ball 46 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=47}] slot.weapon.mainhand 0 vc:slime_ball 47 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=48}] slot.weapon.mainhand 0 vc:slime_ball 48 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=49}] slot.weapon.mainhand 0 vc:slime_ball 49 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=50}] slot.weapon.mainhand 0 vc:slime_ball 50 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=51}] slot.weapon.mainhand 0 vc:slime_ball 51 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=52}] slot.weapon.mainhand 0 vc:slime_ball 52 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=53}] slot.weapon.mainhand 0 vc:slime_ball 53 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=54}] slot.weapon.mainhand 0 vc:slime_ball 54 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=55}] slot.weapon.mainhand 0 vc:slime_ball 55 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=56}] slot.weapon.mainhand 0 vc:slime_ball 56 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=57}] slot.weapon.mainhand 0 vc:slime_ball 57 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=58}] slot.weapon.mainhand 0 vc:slime_ball 58 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=59}] slot.weapon.mainhand 0 vc:slime_ball 59 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=60}] slot.weapon.mainhand 0 vc:slime_ball 60 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=61}] slot.weapon.mainhand 0 vc:slime_ball 61 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=62}] slot.weapon.mainhand 0 vc:slime_ball 62 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=63}] slot.weapon.mainhand 0 vc:slime_ball 63 0
#replaceitem entity @s[hasitem={location=slot.weapon.mainhand,slot=0,item=slime_ball,data=0,quantity=64}] slot.weapon.mainhand 0 vc:slime_ball 64 0
#
#
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=1},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=1}] slot.weapon.mainhand 0 slime_ball 1 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=2},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=2}] slot.weapon.mainhand 0 slime_ball 2 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=3},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=3}] slot.weapon.mainhand 0 slime_ball 3 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=4},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=4}] slot.weapon.mainhand 0 slime_ball 4 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=5},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=5}] slot.weapon.mainhand 0 slime_ball 5 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=6},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=6}] slot.weapon.mainhand 0 slime_ball 6 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=7},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=7}] slot.weapon.mainhand 0 slime_ball 7 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=8},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=8}] slot.weapon.mainhand 0 slime_ball 8 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=9},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=9}] slot.weapon.mainhand 0 slime_ball 9 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=10},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=10}] slot.weapon.mainhand 0 slime_ball 10 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=11},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=11}] slot.weapon.mainhand 0 slime_ball 11 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=12},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=12}] slot.weapon.mainhand 0 slime_ball 12 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=13},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=13}] slot.weapon.mainhand 0 slime_ball 13 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=14},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=14}] slot.weapon.mainhand 0 slime_ball 14 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=15},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=15}] slot.weapon.mainhand 0 slime_ball 15 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=16},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=16}] slot.weapon.mainhand 0 slime_ball 16 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=17},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=17}] slot.weapon.mainhand 0 slime_ball 17 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=18},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=18}] slot.weapon.mainhand 0 slime_ball 18 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=19},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=19}] slot.weapon.mainhand 0 slime_ball 19 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=20},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=20}] slot.weapon.mainhand 0 slime_ball 20 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=21},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=21}] slot.weapon.mainhand 0 slime_ball 21 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=22},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=22}] slot.weapon.mainhand 0 slime_ball 22 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=23},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=23}] slot.weapon.mainhand 0 slime_ball 23 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=24},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=24}] slot.weapon.mainhand 0 slime_ball 24 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=25},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=25}] slot.weapon.mainhand 0 slime_ball 25 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=26},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=26}] slot.weapon.mainhand 0 slime_ball 26 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=27},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=27}] slot.weapon.mainhand 0 slime_ball 27 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=28},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=28}] slot.weapon.mainhand 0 slime_ball 28 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=29},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=29}] slot.weapon.mainhand 0 slime_ball 29 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=30},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=30}] slot.weapon.mainhand 0 slime_ball 30 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=31},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=31}] slot.weapon.mainhand 0 slime_ball 31 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=32},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=32}] slot.weapon.mainhand 0 slime_ball 32 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=33},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=33}] slot.weapon.mainhand 0 slime_ball 33 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=34},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=34}] slot.weapon.mainhand 0 slime_ball 34 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=35},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=35}] slot.weapon.mainhand 0 slime_ball 35 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=36},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=36}] slot.weapon.mainhand 0 slime_ball 36 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=37},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=37}] slot.weapon.mainhand 0 slime_ball 37 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=38},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=38}] slot.weapon.mainhand 0 slime_ball 38 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=39},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=39}] slot.weapon.mainhand 0 slime_ball 39 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=40},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=40}] slot.weapon.mainhand 0 slime_ball 40 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=41},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=41}] slot.weapon.mainhand 0 slime_ball 41 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=42},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=42}] slot.weapon.mainhand 0 slime_ball 42 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=43},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=43}] slot.weapon.mainhand 0 slime_ball 43 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=44},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=44}] slot.weapon.mainhand 0 slime_ball 44 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=45},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=45}] slot.weapon.mainhand 0 slime_ball 45 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=46},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=46}] slot.weapon.mainhand 0 slime_ball 46 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=47},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=47}] slot.weapon.mainhand 0 slime_ball 47 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=48},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=48}] slot.weapon.mainhand 0 slime_ball 48 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=49},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=49}] slot.weapon.mainhand 0 slime_ball 49 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=50},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=50}] slot.weapon.mainhand 0 slime_ball 50 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=51},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=51}] slot.weapon.mainhand 0 slime_ball 51 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=52},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=52}] slot.weapon.mainhand 0 slime_ball 52 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=53},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=53}] slot.weapon.mainhand 0 slime_ball 53 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=54},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=54}] slot.weapon.mainhand 0 slime_ball 54 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=55},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=55}] slot.weapon.mainhand 0 slime_ball 55 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=56},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=56}] slot.weapon.mainhand 0 slime_ball 56 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=57},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=57}] slot.weapon.mainhand 0 slime_ball 57 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=58},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=58}] slot.weapon.mainhand 0 slime_ball 58 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=59},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=59}] slot.weapon.mainhand 0 slime_ball 59 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=60},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=60}] slot.weapon.mainhand 0 slime_ball 60 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=61},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=61}] slot.weapon.mainhand 0 slime_ball 61 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=62},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=62}] slot.weapon.mainhand 0 slime_ball 62 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=63},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=63}] slot.weapon.mainhand 0 slime_ball 63 0
##replaceitem entity @s[hasitem={item=vc:slime_ball,data=0,quantity=64},hasitem={location=slot.weapon.mainhand,slot=0,item=vc:slime_ball,data=0,quantity=64}] slot.weapon.mainhand 0 slime_ball 64 0